CREATE OR REPLACE CONTEXT PLATFORMADMIN_CTX USING PLATFORMADMIN_CTX_PKG;

CREATE OR REPLACE PACKAGE PLATFORMADMIN_CTX_PKG IS
    PROCEDURE SET_PLATFORMADMIN_CONTEXT;
END;
/

CREATE OR REPLACE PACKAGE BODY PLATFORMADMIN_CTX_PKG IS
    PROCEDURE SET_PLATFORMADMIN_CONTEXT IS
        ADMIN_ID NUMBER;
    BEGIN
        SELECT AdminID INTO ADMIN_ID
        FROM PlatformAdmins
        WHERE Username = SYS_CONTEXT('USERENV', 'SESSION_USER');

        DBMS_SESSION.SET_CONTEXT('platformadmin_ctx', 'admin_id', ADMIN_ID);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL; 
    END SET_PLATFORMADMIN_CONTEXT;
END;
/

CREATE OR REPLACE TRIGGER SET_PLATFORMADMIN_CTX_TRIG
AFTER LOGON ON DATABASE
BEGIN
    PLATFORMADMIN_CTX_PKG.SET_PLATFORMADMIN_CONTEXT;
END;
/
