CREATE OR REPLACE CONTEXT STORESTAFF_CTX USING STORESTAFF_CTX_PKG;

CREATE OR REPLACE PACKAGE STORESTAFF_CTX_PKG IS
    PROCEDURE SET_STORESTAFF_CONTEXT;
END;
/

CREATE OR REPLACE PACKAGE BODY STORESTAFF_CTX_PKG IS
    PROCEDURE SET_STORESTAFF_CONTEXT IS
        STAFF_ID NUMBER;
        STORE_ID NUMBER;
        ROLE VARCHAR2(20);
    BEGIN
        SELECT StaffID, StoreID, Role INTO STAFF_ID, STORE_ID, ROLE
        FROM StoreStaff
        WHERE Username = SYS_CONTEXT('USERENV', 'SESSION_USER');

        DBMS_SESSION.SET_CONTEXT('storestaff_ctx', 'staff_id', STAFF_ID);
        DBMS_SESSION.SET_CONTEXT('storestaff_ctx', 'store_id', STORE_ID);
        DBMS_SESSION.SET_CONTEXT('storestaff_ctx', 'role', ROLE);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL; 
    END SET_STORESTAFF_CONTEXT;
END;
/

CREATE OR REPLACE TRIGGER SET_STORESTAFF_CTX_TRIG
AFTER LOGON ON DATABASE
BEGIN
    STORESTAFF_CTX_PKG.SET_STORESTAFF_CONTEXT;
END;
/
